name: Deploy to server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Sync project to server (exclude .env)
        run: |
          rsync -avz --delete --exclude='.git' --exclude='.env' ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_TARGET }}

      - name: Write .env on server and restart backend
        env:
          TARGET: ${{ secrets.SERVER_TARGET }}
        run: |
          # Write .env on the remote server using the OPENAI_API_KEY secret
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<EOF
          cat > $TARGET/.env <<'ENV'
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL=gpt-4o
          ADMIN_TOKEN=secret-token
          RERANK_N=5
          ENV
          # Restart the backend (adjust path/command if your deploy differs)
          pkill -f server_py.py || true
          nohup python3 $TARGET/server_py.py > $TARGET/server.log 2>&1 &
          EOF
